const signoffs = [
  "Ni hablar,",
  "Stay safe,",
  "Utterly,",
  "And remember folks, always spay or neuter your pets,",
  "x",
  "Gobble Gobble,",
  "Think about it and let it simmer,",
  "get twiddled,",
  "unintentionally,",
  "Be reckless,",
  "Don’t be reckless,",
  "Expecto patronum,",
  "To be or not to be,",
  "It’s time,",
  "I'm tired now,",
  "Nothing to see here,",
  "Shasta,",
  "Out of time,",
  "Ciao for now,",
  "Chur Cuz,",
  "Very nice,",
  "Be kind to yourself and take care of the ones around you,",
  "Wish me luck,",
  "All my faith,",
  "Yours in union,",
  "Call your mom,",
  "I promise it'll be cute,",
  "TTFN,",
  "Cheers for real,",
  "LUV U KK BYE NOW",
  "liminally,",
  "It doesn't matter what I think,",
  "All typos in this letter are on purpose actually,",
  "Can you dig it?,",
  "Mind your manners,",
  "Did you fart?,",
  "in these salad days,",
  "stay hydrated",
  "Warmly greetings,",
  "Stay warm,",
  "I end ere I weary you ... Adieu",
  "<em dash><initial>",
  "Something went wrong trying to save thanks.......",
  "Loving poetry always,",
  "Nobody is above the law.",
  "A por ellos que son pocos y cobardes,",
  "Abrazo de gol,",
  "stay golden,",
  "all my best,",
  "a million thanks,",
  "Eagerly,",
  "see you in hell,",
  "comfort first,",
  "maybe,",
  "Fingers crossed,",
  "Take risks,",
  "I'll keep thinking,,,",
  "With love and solidarity,",
  "Sa tagumpay nating lahat,",
  "S.W.A.L.K. (sealed with a loving kiss),",
  "Spuni cuni fait,",
  "As ever,",
  "Yours faithfully",
  "Your patient,",
  "bon appetit,",
  "would be funny if we’re cousins,",
  "Fantically-- or fanatically--↵Yours for a better world,↵Before we have to settle for Any--",
  "Your slave and enemy,",
  "All, always",
  "Dear children, keep yourselves from idols,",
  "Forever over-caffeinated,",
  "I wish you calm seas, following winds, and a happy voyage through life",
  "Unenamored",
  "all the best through the server from the heart,",
  "bye, I love everything,",
  "Toward better worlds,",
  "Always forward,",
  "From the dog days of summer,",
  "Thank Dog Heaven Monday is over,",
  "Hope this message finds u in a jacuzzi,",
  "Our souls are unbound and words make it limiting,",
  "Best (I'm the),",
  "Please release me from my pain,",
  "Long live the Queen,",
  "Your boy,",
  "Death to the enemy,",
  "```",
  "Sent from my toaster,",
  "in this moment,",
  "Warmest,",
  "Poopity scoop!",
  "don't mind me,",
  "thanks for everything,",
  "To infinity and beyond,",
  "Birds in flight,",
  "Alright!",
  "Blessings,",
  "Etc.,",
  "Look forward,",
  "Duly nutted,",
  "Always searching,",
  "Branches in the sky, roots in the ground, eyes beyond the world,",
  "Don't forget your towel,",
  "Always forward,",
  "Tips Hat,",
  "Godspeed,",
  "See you soon, crocodile",
  "Ad ventura,",
  "Ad astra,",
  "Per aspera ad astra,",
  "Mango slices and lakes to lounge in,",
  "Until an asteroid,",
  "Love this thing,",
  "Minutes aren't limits,",
  "Indefinitely,",
  "Ashes to ashes dust to dust,",
  "Be kind to animals,",
  "Notwithstanding,",
  "Now more than ever,",
  "Thanks already",
  "Yours in the long meantime,",
  "I am,",
  "it's me,",
  "okie,",
  "*bell sound*,",
  "Thanks forward,",
  "https:// www.are.na/meg-miller/good-sign-offs,",
  "Look me up after armageddon,",
  "under the cloudy vale,",
  "Best in spirit,",
  "o,",
  "( ु⁎ᴗ_ᴗ⁎)ु.｡oO,",
  "eat well,",
  "Nondimensionalizing,",
  "Eat, pray, love,",
  "No problems- only solutions,",
  "Cool,",
  "Blue skies,",
  "to my enemies",
  "Wind over water,",
  "A day just like today,",
  "Optimistically yours,",
  "All in,",
  "All things considered,",
  "lessgo,",
  "Best on a sort of sunny Saturday,",
  "LOL",
  "With maximum floor-area-ratio,",
  "With love and understanding,",
  "In utopian conspiracy,",
  "until more,",
  "🎩,",
  "With hope,",
  "Life experience until I die,",
  "++",
  "Dis-moi,",
  "Bad boys afloat,",
  "Peace up a town down",
  "Cheering you on,",
  "Good vibes,",
  "Yours in Piscean thoughts,",
  "Keep the faith,",
  "salam,",
  "nolite timere,",
  "always,",
  "Under sunshine,",
  "Stay warm in your heart and cozy in your bed,",
  "do the needful,",
  "Courage,",
  "No hard feelings,",
  "Happy to discuss,",
  "Talk soon PenPal B!",
  "As before, so again,",
  "On that note!",
  "Mahalo nui loa,",
  "Aloha,",
  "thanks for all the fish,",
  "bis bis,",
  "bis bald,",
  "ok,",
  "Three wishes,",
  "FYSA ily xoxo.",
  "Gruß,",
  "all my best,",
  "Charmed,",
  "Tinkety tonk old fruit & down with the Nazis,",
  "Glistening,",
  "Until soon,",
  "No, it’s fine, really,",
  "All my love,",
  "Gusto,",
  "Thanks, you’re a million",
  "From my lap, with love,",
  "I have the honour to be your obedient servant,",
  "with gratitude,",
  "We’ll burn that bridge when we get to it",
  "Sent from my thingy",
  "Soon,",
  "Waiting for your reply,",
  "Sent from iPhone",
  "ok, truly enough.",
  "Easy,",
  "May the long time sunshine on you,",
  "I think the the universe has experienced enough for today I'm out.",
  "Good things,",
  "Until next time,",
  "A cool breeze,",
  "Giddy up,",
  "Sunshine always,",
  "We'll keep / stay in touch.",
  "I'll send you the link,",
  "See you online,",
  "Veuillez agréer, Madame, Monsieur, mes salutations les plus distinguées.",
  "This is an automatic email confirmation.",
  "sending gossamer butterflies of love and laughter,",
  "Ride high,",
  "So far, so bueno,",
  "And then what,",
  "May the sun shine warm upon your face,",
  "Over and out.",
  "All do Respect, Love, and Admiration,",
  "Dictated but not read.",
  "Birds chirping,",
  "Liäbi Grüäss,",
  "A gong will sound when I press send,",
  "Waiting for the sun to set,",
  "See you / Be you,",
  "Stay gold,",
  "Siempre,",
  "Truly madly deeply,",
  "banner salutations,",
  "peace and plastic bricks,",
  "Running around, trying not to get hit,",
  "I remain,",
  "Yours in abandon,",
  "Kind wishes from the HQ,",
  "Free and easy wandering,",
  "I'm going on a short vacation. Please don't look for me,",
  "warmth,",
  "Thank you to the people that let me know it was wrong.↵Rocio",
  "Peace, mucho love and remember where you came from––the womb,"
]

InboxSDK.load(2, 'sdk_good-signoffs_c71abb4fbd').then(function(sdk){

  sdk.Compose.registerComposeViewHandler(function(composeView){

    const statusBar = composeView.addStatusBar()
      statusBar.el.style.borderTop = '1px solid #c3c3c3'
      statusBar.el.style.paddingTop = '10px'

    const button = document.createElement('img')
      button.src = 'https://freepngimg.com/thumb/ryan_gosling/31624-7-ryan-gosling-image.png'
      button.setAttribute('style', 'height: 24px; padding: 3px; border-radius: 3px; cursor: pointer; background-color: #F9F8F6')
      button.addEventListener('click', () => {
        const randomSignoff = signoffs[Math.floor(Math.random() * signoffs.length)]
        composeView.insertTextIntoBodyAtCursor(randomSignoff);
      })

    statusBar.el.appendChild(button)

    // composeView.addButton({
    //   title: "My Nifty Button!",
    //   iconUrl: 'https://freepngimg.com/thumb/ryan_gosling/31624-7-ryan-gosling-image.png',
    //   onClick: function(event) {
    //     event.composeView.insertTextIntoBodyAtCursor('Hello World!');
    //   },
    // });

  });

});
